### ISSUE TITLE
Sync local <- remote : not working

### ISSUE THREAD

**Issue by tomhaerter** [icetee/remote-ftp#1016]
# download files does weird stuff:

![error](https://user-images.githubusercontent.com/16882922/31455844-34927752-aeb9-11e7-94b3-a321009674a9.png)

**Comment by Gimenez-Alex** [comment]
I have also the same problem with the version 1.2.5

**Comment by ashishsajwan** [comment]
+1

Need fix badly or i'll go back to sublime

**Comment by ashishsajwan** [comment]
https://github.com/icetee/remote-ftp/issues/997

**Comment by kucits** [comment]
@ashishsajwan - this isn't an issue with Atom... it's an issue with the Remote FTP plugin.

**Comment by sfoley** [comment]
Same here. 1.1.3 seems to work correctly with Atom 1.21.1 though.

**Comment by icetee** [comment]
Try v1.2.6!

**Comment by sfoley** [comment]
Updated to 1.2.6 just now, restarted atom, but still the same behavior when I sync local <-remote for a directory tree...the subdirectories seem to fall out of their structure, same as in 1.2.4.

**Comment by brunotda** [comment]
Bug was not fixed in version 1.2.6 @icetee

**Comment by AndreasBottcher** [comment]
agree, not fixed
@icetee

**Comment by freexmonster** [comment]
realy krashed bug! because of this I lost 2 hours and was very upset

**Comment by arzhed** [comment]
+1 with 1.2.6. Went back to 1.1.3 looks like it works fine

**Comment by icetee** [comment]
Resolved >= v1.3.0

**Comment by nbdamian** [comment]
@icetee The issue is still occurring on 1.3.1, The issue occurs when downloading a folder with subfolders, and files inside of those subfolders.

**Comment by AndreasBottcher** [comment]
@nbdamian @icetee just now tried v 1.3.1... The bug is still undefeated :(
Went back to 1.1.3.

**Comment by AndreasBottcher** [comment]
@icetee i tried again, for FTP v1.3.1 works fine, but not for SFTP...

**Comment by icetee** [comment]
@AndreasBottcher Ohh, this is useful info. In the evening I look at you thank you.

**Comment by icetee** [comment]
Fix it for SFTP https://github.com/icetee/remote-ftp/releases/tag/v1.3.2
Can you test it?

**Comment by Xsander** [comment]
Hello, just installed pre-release by your link and can confirm that sync local <= remote works now, it downloaded filders and files, but there was strange folder with name 's' that don'exists on remote side.
that showed me errors resolving symlinks

-- now remote directory listing working totally slow. it takes about 3 minutes to open remote fiolder with 3 subfolders and near 10 files
--edit 
remote directory listing works fine after atom restart. don't know how to reproduce, but it slowed right after sync from remote to local

--added

upload on save works fine, but direct Upload command not working when creating local file and trying to upload. 
i'm using macOS High Sierra, latest atom 1.22.1

**Comment by icetee** [comment]
@Xsander Direct upload fix. https://github.com/icetee/remote-ftp/issues/942

**Comment by renathoaz** [comment]
is there any way to change Sync local <-Remote destination folder,
When I sync from remote panel to local, the package saves my project in .atom, not in local project.
is there any way to change it or link it to the desired folder ?
