### ISSUE TITLE
Softlinks are displayed as Files and if you klick on them it downloads the complete target directory instead of changing into the directory

### ISSUE THREAD

**Issue by geoschwa** [icetee/remote-ftp#268]

**Comment by jpxd** [comment]
Symlinks should be working with SFTP after the new update (v0.7.16)

**Comment by geoschwa** [comment]
There's still a problem with symlinks. At least in version 0.7.20
Symlinks are not relsolved properly. It always puts the current working directory in front of the path to the target of the link.

![image](https://cloud.githubusercontent.com/assets/16822105/13169975/422dabc4-d6e9-11e5-8b6c-b8f9d597bf70.png)
