### ISSUE TITLE
Uncaught ReferenceError: log is not defined

### ISSUE THREAD

**Issue by pruge** [icetee/remote-ftp#49]
[Enter steps to reproduce below:]
1. try to change name remote folder.
2. cannot connect again.

**Atom Version**: 0.182.0
**System**: window 7 64bit
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.1
### Stack Trace

Uncaught ReferenceError: log is not defined

```
At C:\Users\Administrator\.atom\packages\Remote-FTP\lib\client.js:176

ReferenceError: log is not defined
    at info.debug (C:\Users\Administrator\.atom\packages\Remote-FTP\lib\client.js:176:20)
    at self.info.debug (C:\Users\Administrator\.atom\packages\Remote-FTP\lib\connectors\ftp.js:55:22)
    at Socket.ondata (C:\Users\Administrator\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:279:12)
    at Socket.emit (events.js:116:17)
    at readableAddChunk (_stream_readable.js:164:16)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:530:20)
```
### Commands

```
     -0:23.9 remote-ftp:toggle (atom-text-editor.editor)
     -0:21.6 application:open-folder (atom-text-editor.editor)
     -0:09.8 remote-ftp:toggle (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "remote-edit",
      "remote-sync"
    ]
  },
  "Remote-FTP": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.1

# Dev
No dev packages
```

**Comment by phawxby** [comment]
Fixed in a8640a01227948281efb82c7d9fdb9faeb3c5297

**Comment by chinex-eze** [comment]
I still have the problem. I uninstalled atom and installed again just now. 
I also checked for updates and it reports that all of my installed packages are up to date. 

Would really appreciate any help. 
Thanks

**Comment by phawxby** [comment]
I think you'll need to wait for @mgrenier to publish an update. I don't have rights to do so

**Comment by phawxby** [comment]
In the meantime download the entire source code from here or my fork.

Navigate to "C:\Users\[USERNAME]\.atom\packages\remote-ftp" and delete all the contents then put all the downloaded source in there. It'll get it working again until an update is published

**Comment by chinex-eze** [comment]
Yess! Now it works :+1: 
thanks alot

**Comment by Manoj-nathwani** [comment]
What version is safe to roll back to until a fix is released?

**Comment by Manoj-nathwani** [comment]
Worked for me too! Thanks. This package is awesome :+1:

**Comment by vahidvalian** [comment]
I use remote-ftp to connect to remote server, but when I click on Connect link, getting this error Uncaught ReferenceError: log is not defined

**Comment by phawxby** [comment]
@vtworockman see my instructions above. It'll get it working until @mgrenier publishes an update, which I'm hoping will be soon seeing as the current package is broken.

Edit: @mgrenier if you don't have time I'll be willing to publish if you give me access. I've never done it before but I'll figure it out!

**Comment by ghost** [comment]
I got the same error and modified `client.js` as @phawxby proposed and it work very well! This package is a **must have** for me, but will not work without this fix.
